sam/sam/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static

from . import settings
import events.urls
import users.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include(users.urls, namespace="users")),
    url(r'^events/', include(events.urls, namespace="events"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sam/events/models.py
# -*- coding: utf-8 -*-
import uuid
from django.db import models
from users.models import Customer, Dealer
from django.contrib.auth.models import User
from datetime import datetime  

def get_picture_path(instance, filename):
    """ this function is derived from a function by amirali moinfar for webcourse spring 2015."""
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return 'pictures/' + filename


class Category(models.Model):
    name = models.CharField(u"نام دسته", max_length=255, null=False, blank=False)

    class Meta:
        verbose_name = u"دسته"
        verbose_name_plural = u"دسته‌ها"
    def __str__(self):
        return self.name
    def __unicode__(self):
            return u"دسته {}".format(self.name)


class Subcategory(models.Model):
    name = models.CharField(u"نام زیردسته", max_length=255, null=False, blank=False)

    category = models.ForeignKey(Category,null=True,blank=True)

    class Meta:
        verbose_name = u"زیردسته"
        verbose_name_plural = u"زیردسته‌ها"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u"زیردسته‌ی {} در دسته‌ی {}".format(self.name, self.category.name)


class Event(models.Model):
    ACCEPTED = 0
    REJECTED = 1
    PENDING = 2
    CONDITION_CHOICES = (
        (ACCEPTED, u"تأیید"),
        (REJECTED, u"رد شده"),
        (PENDING, u"بررسی"),
    )
    name = models.CharField(u"نام رویداد", max_length=255, null=False, blank=False)
    address = models.TextField(u"آدرس", null=False, blank=False)
    neighborhood = models.CharField(u"نام محله\خلاصه‌ی مکان", max_length=50, null=False, blank=False)
    description = models.TextField(u"توضیحات", null=False, blank=False)
    condition = models.IntegerField(u"وضعیت", choices=CONDITION_CHOICES, default=2, null=False, blank=False)
    condition_description = models.TextField(u"توضیحات وضعیت", null=True, blank=True)
    verification_file = models.FileField(u"مدرک اعتبار سنجی", null=True, blank=True)
    latitude = models.FloatField(u"عرض جغرافیایی", null=False, blank=False)
    longitude = models.FloatField(u"طول جغرافیایی", null=False, blank=False)
    phone_number = models.CharField(u"شماره تلفن", max_length=12, null=False, blank=False)

    subcategory = models.ForeignKey(Subcategory)
    dealer = models.ForeignKey(Dealer)

    class Meta:
        verbose_name = u"رویداد"
        verbose_name_plural = u"رویدادها"

    def __unicode__(self):
        return u"رویداد {} ".format(self.name)

    def __repr__(self):
        return self.__unicode__()

    def first_picture(self):
        return EventPicture.objects.filter(event=self).first()

    def first_date(self):
        return TicketType.objects.filter(event=self).order_by('datetime').first().datetime.date()

    def cheapest_ticket(self):
        return TicketType.objects.filter(event=self).order_by('price').first().price

    def total_number_of_tickets(self):
        return TicketType.objects.filter(event=self).aggregate(models.Sum('total'))['total__sum']

    def available_tickets(self):
        return TicketType.objects.filter(event=self).aggregate(models.Sum('available'))['available__sum']

    def sold_tickets_number(self):
        return self.total_number_of_tickets() - self.available_tickets()

    def category(self):
        return self.subcategory.category.name

    def rating(self):
        temp = 0
        for rate in self.rate_set.all():
            temp+=rate.rate_number
        if self.rate_set.count()>0:
            return int(temp/self.rate_set.count())
        else:
            return 4


class EventPicture(models.Model):
    picture = models.ImageField(u"تصویر", upload_to=get_picture_path, null=False, blank=False)
    event = models.ForeignKey(Event)

    class Meta:
        verbose_name = u"تصویر رویداد"
        verbose_name_plural = u"تصاویر رویدادها"

    def __unicode__(self):
        return u"تصویر برای رویداد {}".format(self.event.name)


class TicketType(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    total = models.IntegerField(u"تعداد کل", null=False, blank=False)
    available = models.IntegerField(u"موجود", null=False, blank=False)
    datetime = models.DateTimeField(u"زمان", null=False, blank=False)
    price = models.IntegerField(u"قیمت", null=False, blank=False)

    event = models.ForeignKey(Event)

    class Meta:
        verbose_name = u"نوع‌بلیط"
        verbose_name_plural = u"نوع‌بلیط‌ها"

    def __unicode__(self):
        return u"بلیط {} از رویداد {}".format(self.name, self.event.name)
    
    def buy(self, bought):
        self.available = self.available - bought
        self.save()
        
    def cancel(self):
        self.available = self.available + 1
        
class Order(models.Model):
    datetime = models.DateTimeField(u"زمان", default=datetime.now, null=False, blank=False)

    event = models.ForeignKey(Event)
    customer = models.ForeignKey(Customer)

    class Meta:
        verbose_name = u"سفارش"
        verbose_name_plural = u"سفارش‌ها"


class Ticket(models.Model):
    column = models.IntegerField(u"ستون", null=True, blank=True)
    row = models.IntegerField(u"ردیف", null=True, blank=True)

    event = models.ForeignKey(Event)
    order = models.ForeignKey(Order)
    type = models.ForeignKey(TicketType, null=True)
    
    
    class Meta:
        verbose_name = u"بلیط"
        verbose_name_plural = u"بلیط‌ها"

class Comment(models.Model):
    text = models.TextField(u"متن", null=False, blank=False)
    datetime = models.DateTimeField(u"زمان", null=False, blank=False)

    event = models.ForeignKey(Event)
    customer = models.ForeignKey(Customer)

    class Meta:
        verbose_name = u"نظر"
        verbose_name_plural = u"نظرها"


class Rate(models.Model):
    rate_number = models.IntegerField(null=False, blank=False)

    event = models.ForeignKey(Event)
    customer = models.ForeignKey(Customer)

    class Meta:
        verbose_name = u"امتیاز"
        verbose_name_plural = u"امتیازها"

sam/templates/dealer_profile_parts/dealer_events.html
{% for event in allevents %}
    {% if event.dealer == profile_user %}
        {% include 'event_row_parts/event_row_condition_dealer.html' with event=event %}
    {% endif %}
{% endfor %}

sam/templates/dealer_profile_parts/dealer_reports.html
<br>
<form class="form">
    <div class="form-inline">
        <div class="form-group">
            <label for="report-type">نوع گزارش</label>
            <select class="form-control" id="report-type">
                <option> گزارش فروش کل </option>
                <option> گزارش فروش دسته </option>
                <option> گزارش فروش زیردسته</option>
                <option>گزارش فروش بر حسب زمان</option>
            </select>
        </div>
    </div>
    <br>
    <div class="form-inline">
        <div class="form-group">
            <label for="category"> دسته </label>
            <select class="form-control" id="category" disabled>
                <option> کنسرت </option>
                <option> تئاتر </option>
                <option> سینما </option>
            </select>
        </div>
    </div>
    <br>
    <div class="form-inline">
        <div class="form-group">
            <label for="from"> از </label>
            <input type="date" class="form-control" id="from" placeholder="از" disabled>
            <label for="to"> تا </label>
            <input type="date" class="form-control" id="to" placeholder="تا" disabled>
        </div>
    </div>
    <br>
    <button type="submit" class="btn btn-success">دریافت گزارش</button>
</form>

<div class="row">
    <br>


</div>

sam/templates/dealer_profile_parts/register_event.html
{% load farsi_num %}
<script type="text/javascript">
    function configureDropDownLists(ddl1,ddl2) {
        switch (ddl1.value) {
            {% for category in categories %}
            case "{{ category.id }}":
                ddl2.options.length = 0;
                {% for subcat in category.subcategory_set.all %}
                    createOption(ddl2, "{{ subcat.name }}", {{ subcat.id }});
                {% endfor %}
                break;
            {% endfor %}
        }

    }

    function createOption(ddl, text, value) {
        var opt = document.createElement('option');
        opt.value = value;
        opt.text = text;
        ddl.options.add(opt);
    }
</script>


<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-11">
    <br>
    <form name="register_event" method="post" action="{% url 'events:register_event' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-inline">
            <div class="form-group">
                <label for="category"> دسته </label>
                <select name="category" class="form-control" id="category" onchange="configureDropDownLists(this,document.getElementById('subcategory'))">
                    {% for category in categories %}
                        <option value="{{ category.id }}"> {{ category.name }} </option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <br>
        {% with categories.all|first as first_category %}
            <div class="form-inline">
                <div class="form-group">
                    <label for="category">زیردسته</label>
                    <select name="subcategory" class="form-control" id="subcategory">

                        {% for subcat in first_category.subcategory_set.all %}
                            <option value="{{ subcat.id }}"> {{ subcat.name }} </option>
                        {% endfor %}

                    </select>
                </div>
            </div>
        {% endwith %}
        </br>
        {{ eventform }}
        </br>
        <div id="add-ticket-type" class="btn btn-info"> افزودن نوع بلیط </div>

        <div>
            <ul id="sam-ticket-types">

            </ul>
        </div>
        <br>

        <div id="add-picture" class="btn btn-info">افزودن تصویر</div>

        <div>
            <ul id="sam-pictures">

            </ul>
        </div>

        <br>
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-success col-md-12"> ثبت </button>
                </div>
            </div>
        </div>
        <div><h5></h5></div>
    </form>
  </div>
</div>