sam/events/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register_event/$', views.register_event, name="register_event"),
    url(r'event_small_card/$', views.event_cards, name='event_small_card'),
    url(r'event_row_verify/$', views.event_row_verify, name='event_row_verify'),
    url(r'event_row_condition/$', views.event_row_condition, name='event_row_condition'),
    url(r'event_row_purchase/$', views.event_row_purchase, name='event_row_purchase'),
    url(r'event_row_print/$', views.event_row_print, name='event_row_print'),
    url(r'event_cards/$', views.event_cards, name='event_cards'),
    url(r'^edit_details/(?P<event_id>\d+)/$', views.edit_details, name="edit_details"),
    url(r'^edit_event/(?P<event_id>\d+)/(?P<done>\d+)$', views.event_edit_page, name='event_edit'),
    url(r'event_row_verify/$', views.event_row_verify, name='event_row_verify'),
    url(r'^remove_category/$', views.remove_category, name='remove_category'),
    url(r'^subcategory/(?P<category_id>([0-9])+)/(?P<subcategory_id>([0-9])+)/$', views.show_subcategory, name='show_subcategory'),
    url(r'^(?P<event_id>\d+)/$', views.event_view, name='event_view'),
    url(r'^delete_event/(?P<event_id>\d+)/$', views.delete, name='delete'),
    url(r'^info_template/', views.info_template, name="info_template"),
]

sam/sam/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static

from . import settings
import events.urls
import users.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include(users.urls, namespace="users")),
    url(r'^events/', include(events.urls, namespace="events"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sam/users/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^login/$', 'users.views.login', name="login"),
    url(r'^logout/$', 'users.views.logout', name="logout"),
    url(r'^test/signup', 'users.views.signup', name='signup'),
    url(r'^signup/customer', 'users.views.signup_customer', name='signup_customer'),
    url(r'^signup/dealer', 'users.views.signup_dealer', name='signup_dealer'),
    url(r'^home/$', 'users.views.home', name='home'),
    url(r'^show_profile/$', 'users.views.show_profile', name='show_profile'),
    url(r'^ticket/(?P<return_code>\d+)/$', 'users.views.print_ticket', name='ticket'),
    url(r'^test/home/user/$', 'users.views.home_log_out', name='homelogout'),
    url(r'^payment/successful/$', 'users.views.payment_success', name='success'),
    url(r'^payment/$', 'users.views.payment', name='payment'),
    url(r'^cancel_payment/$', 'users.views.cancel_payment', name='cancel_payment'),
    url(r'^test/search/category/subcategory/$', 'users.views.search', name='testsearch'),
    url(r'^test/menu/$', 'users.views.menu', name='test'),
    url(r'^test/customer/$', 'users.views.customer_profile', name='test_customer'),
    url(r'^test/dealer/$', 'users.views.dealer_profile', name='test'),
    url(r'^test/admin/$', 'users.views.admin', name='test_admin'),
    url(r'^test/$', 'users.views.test', name='test'),
    url(r'^admin/$', 'users.views.admin', name='admin'),
    url(r'^profile/username', 'users.views.customer_profile', name='customer_profile'),
    url(r'^profile/dealer', 'users.views.dealer_profile', name='dealer_profile'),
    url(r'^add_category', 'users.views.add_category', name='add_category'),
    url(r'^add_subcategory', 'users.views.add_subcategory', name="add_subcategory"),
    url(r'^edit_category', 'users.views.edit_category', name="edit_category"),
    url(r'^edit_subcategory', 'users.views.edit_subcategory', name="edit_category"),
    url(r'^editCat/(?P<catpk>[-\w]+)/all_json_subs/$', 'users.views.all_json_subs'),
    url(r'^remove_subcategory', 'users.views.remove_subcategory', name="remove_category"),
    url(r'^removeCat/(?P<catpk>[-\w]+)/all_json_subs/$', 'users.views.all_json_subs'),
    url(r'^edit_profile', 'users.views.edit_profile', name='edit_profile'),
    url(r'^submit_edit_profile', 'users.views.submit_edit_profile', name='submit_edit_profile'),
    url(r'^admin_comment/', 'users.views.admin_comment', name="admin_comment"),
]

sam/events/models.py
# -*- coding: utf-8 -*-
import uuid
from django.db import models
from users.models import Customer, Dealer
from django.contrib.auth.models import User
from datetime import datetime  

def get_picture_path(instance, filename):
    """ this function is derived from a function by amirali moinfar for webcourse spring 2015."""
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return 'pictures/' + filename


class Category(models.Model):
    name = models.CharField(u"نام دسته", max_length=255, null=False, blank=False)

    class Meta:
        verbose_name = u"دسته"
        verbose_name_plural = u"دسته‌ها"
    def __str__(self):
        return self.name
    def __unicode__(self):
            return u"دسته {}".format(self.name)


class Subcategory(models.Model):
    name = models.CharField(u"نام زیردسته", max_length=255, null=False, blank=False)

    category = models.ForeignKey(Category,null=True,blank=True)

    class Meta:
        verbose_name = u"زیردسته"
        verbose_name_plural = u"زیردسته‌ها"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u"زیردسته‌ی {} در دسته‌ی {}".format(self.name, self.category.name)


class Event(models.Model):
    ACCEPTED = 0
    REJECTED = 1
    PENDING = 2
    CONDITION_CHOICES = (
        (ACCEPTED, u"تأیید"),
        (REJECTED, u"رد شده"),
        (PENDING, u"بررسی"),
    )
    name = models.CharField(u"نام رویداد", max_length=255, null=False, blank=False)
    address = models.TextField(u"آدرس", null=False, blank=False)
    neighborhood = models.CharField(u"نام محله\خلاصه‌ی مکان", max_length=50, null=False, blank=False)
    description = models.TextField(u"توضیحات", null=False, blank=False)
    condition = models.IntegerField(u"وضعیت", choices=CONDITION_CHOICES, default=2, null=False, blank=False)
    condition_description = models.TextField(u"توضیحات وضعیت", null=True, blank=True)
    verification_file = models.FileField(u"مدرک اعتبار سنجی", null=True, blank=True)
    latitude = models.FloatField(u"عرض جغرافیایی", null=False, blank=False)
    longitude = models.FloatField(u"طول جغرافیایی", null=False, blank=False)
    phone_number = models.CharField(u"شماره تلفن", max_length=12, null=False, blank=False)

    subcategory = models.ForeignKey(Subcategory)
    dealer = models.ForeignKey(Dealer)

    class Meta:
        verbose_name = u"رویداد"
        verbose_name_plural = u"رویدادها"

    def __unicode__(self):
        return u"رویداد {} ".format(self.name)

    def __repr__(self):
        return self.__unicode__()

    def first_picture(self):
        return EventPicture.objects.filter(event=self).first()

    def first_date(self):
        return TicketType.objects.filter(event=self).order_by('datetime').first().datetime.date()

    def cheapest_ticket(self):
        return TicketType.objects.filter(event=self).order_by('price').first().price

    def total_number_of_tickets(self):
        return TicketType.objects.filter(event=self).aggregate(models.Sum('total'))['total__sum']

    def available_tickets(self):
        return TicketType.objects.filter(event=self).aggregate(models.Sum('available'))['available__sum']

    def sold_tickets_number(self):
        return self.total_number_of_tickets() - self.available_tickets()

    def category(self):
        return self.subcategory.category.name

    def rating(self):
        temp = 0
        for rate in self.rate_set.all():
            temp+=rate.rate_number
        if self.rate_set.count()>0:
            return int(temp/self.rate_set.count())
        else:
            return 4


class EventPicture(models.Model):
    picture = models.ImageField(u"تصویر", upload_to=get_picture_path, null=False, blank=False)
    event = models.ForeignKey(Event)

    class Meta:
        verbose_name = u"تصویر رویداد"
        verbose_name_plural = u"تصاویر رویدادها"

    def __unicode__(self):
        return u"تصویر برای رویداد {}".format(self.event.name)


class TicketType(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    total = models.IntegerField(u"تعداد کل", null=False, blank=False)
    available = models.IntegerField(u"موجود", null=False, blank=False)
    datetime = models.DateTimeField(u"زمان", null=False, blank=False)
    price = models.IntegerField(u"قیمت", null=False, blank=False)

    event = models.ForeignKey(Event)

    class Meta:
        verbose_name = u"نوع‌بلیط"
        verbose_name_plural = u"نوع‌بلیط‌ها"

    def __unicode__(self):
        return u"بلیط {} از رویداد {}".format(self.name, self.event.name)
    
    def buy(self, bought):
        self.available = self.available - bought
        self.save()
        
    def cancel(self):
        self.available = self.available + 1
        
class Order(models.Model):
    datetime = models.DateTimeField(u"زمان", default=datetime.now, null=False, blank=False)

    event = models.ForeignKey(Event)
    customer = models.ForeignKey(Customer)

    class Meta:
        verbose_name = u"سفارش"
        verbose_name_plural = u"سفارش‌ها"


class Ticket(models.Model):
    column = models.IntegerField(u"ستون", null=True, blank=True)
    row = models.IntegerField(u"ردیف", null=True, blank=True)

    event = models.ForeignKey(Event)
    order = models.ForeignKey(Order)
    type = models.ForeignKey(TicketType, null=True)
    
    
    class Meta:
        verbose_name = u"بلیط"
        verbose_name_plural = u"بلیط‌ها"

class Comment(models.Model):
    text = models.TextField(u"متن", null=False, blank=False)
    datetime = models.DateTimeField(u"زمان", null=False, blank=False)

    event = models.ForeignKey(Event)
    customer = models.ForeignKey(Customer)

    class Meta:
        verbose_name = u"نظر"
        verbose_name_plural = u"نظرها"


class Rate(models.Model):
    rate_number = models.IntegerField(null=False, blank=False)

    event = models.ForeignKey(Event)
    customer = models.ForeignKey(Customer)

    class Meta:
        verbose_name = u"امتیاز"
        verbose_name_plural = u"امتیازها"

sam/templates/admin_profile.html
{% extends 'base.html' %}
{% load static %}

{% block right_sidebar %}

    <div class="row">
        {% include 'right_sidebar_profile_admin.html' %}
    </div>
{% endblock %}

{% block main_column %}
    <script>
    $(document).ready(function() {
    if(location.hash) {
        $('a[href=' + location.hash + ']').tab('show');
        setTimeout(function() {

        window.scrollTo(0, 0);
        }, 1);
    }
    $(document.body).on("click", "a[data-toggle]", function(event) {
        location.hash = this.getAttribute("href");
    });
});
$(window).on('popstate', function() {
    var anchor = location.hash || $("a[data-toggle=tab]").first().attr("href");
    $('a[href=' + anchor + ']').tab('show');
});
</script>
    <div>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#add_category" aria-controls="add_category" role="tab" data-toggle="tab">افزودن دسته</a></li>
            <li role="presentation"><a href="#remove_category" aria-controls="remove_category" role="tab" data-toggle="tab">حذف دسته‌</a></li>
            <li role="presentation"><a href="#edit_category" aria-controls="edit_category" role="tab" data-toggle="tab">ویرایش دسته‌</a></li>
            <li role="presentation"><a href="#report" aria-controls="report" role="tab" data-toggle="tab"> گزارش </a></li>
            <li role="presentation"><a href="#checking-events" aria-controls="checking-events" role="tab" data-toggle="tab">رویداهای منتظر بررسی</a></li>
            <li role="presentation"><a href="#events" aria-controls="events" role="tab" data-toggle="tab">لیست رویدادها</a></li>
            <li role="presentation"><a href="#users" aria-controls="users" role="tab" data-toggle="tab">لیست کاربران</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="add_category">{% include 'admin_profile_parts/add_category.html' %}</div>
            <div role="tabpanel" class="tab-pane" id="remove_category">{% include 'admin_profile_parts/remove_category.html' %}</div>
            <div role="tabpanel" class="tab-pane" id="edit_category">{% include 'admin_profile_parts/edit_category.html' %}</div>
            <div role="tabpanel" class="tab-pane" id="report"> {% include 'admin_profile_parts/report.html' %} </div>
            <div role="tabpanel" class="tab-pane" id="checking-events">{% include 'admin_profile_parts/checking-events.html' with allevents=allevents %}</div>
            <div role="tabpanel" class="tab-pane" id="events">{% include 'admin_profile_parts/events.html' with allevents=allevents %}</div>
            <div role="tabpanel" class="tab-pane" id="users">{% include 'admin_profile_parts/users.html' with allevents=allevents allusers=allusers %}</div>
        </div>

    </div>
{% endblock %}

sam/templates/event_big_card.html
{% load farsi_num %}

<div class="col-md-12 sam-border">
    <div class="thumbnail sam-event-big-card">
        <div class="row">
            <div class="col-md-8">
                <div id="carousel-event-big-card" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        {% for image in event.eventpicture_set.all %}
                        {% if forloop.counter0 == 0 %}
                        <li data-target="#carousel-event-big-card" data-slide-to="0" class="active"></li>
                        {% endif %}
                        {% if forloop.counter0 != 0 %}
                        <li data-target="#carousel-event-big-card" data-slide-to="{{forloop.counter0}}"></li>
                        {% endif %}
                        {% endfor %}
                    </ol>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        {% for image in event.eventpicture_set.all %}
                        {% if forloop.counter0 == 0 %}
                        <div class="item active">
                            <a href= {% url 'events:event_view' event.id %}>
                               <img src="{{ image.picture.url }}">
                            </a>
                        </div>
                        {% endif %}
                        {% if forloop.counter0 != 0 %}
                        <div class="item">
                            <a href= {% url 'events:event_view' event.id %}>
                                <img src="{{ image.picture.url }}">
                            </a>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-event-big-card" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-event-big-card" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-md-4 sam-border">
                <ol class="breadcrumb">
                    <li><a href="{% url 'events:show_subcategory' event.subcategory.category.id 0 %}">{{event.category}}</a></li>
                    <li><a href="{% url 'events:show_subcategory' event.subcategory.category.id event.subcategory.id%}">{{event.subcategory.name}}</a></li>
                </ol>
                <h2>
                    <a href= {% url 'events:event_view' event.id %}>
                        {{event.name | farsi_num}} <small class="badge">{{event.neighborhood | farsi_num}}</small>
                    </a>
                </h2>
                <br>
                <div class="sam-event-big-card-detail">
                    <div class="row">
                        <div class="col-md-2 ">
                            <h2><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></h2>
                        </div>
                        <div class="col-md-4">
                            <h2>{{event.sold_tickets_number | farsi_num}}</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2">
                            <h2><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></h2>
                        </div>
                        <div class="col-md-4">
                            <h2>{{event.first_date|farsi_num}}</h2>
                        </div>
                    </div>
                </div>
                <div id="event_score" class="raty-star"> </div>
                <div class="sam-price-place">
                    <h2><small>
                        از
                        </small>
                        <span class="sam-price-number">
                        {{event.cheapest_ticket|farsi_num}}
                        </span>
                        <small>
                        تومان
                        </small>
                    </h2>
                </div>
                {% if request.user.is_authenticated %}
                <button type="button" class="btn btn-success btn-lg btn-block" data-toggle="modal" data-target="#price-details">
                خرید کنید
                </button>
                {% endif %}
                {% if not request.user.is_authenticated %}
                <a href="{% url 'users:login' %}">
                    <button type="button" class="btn btn-success btn-lg btn-block">
                     خرید کنید
                    </button>
                </a>
                {% endif %}
                <!-- Modal -->
                <div class="modal fade" id="price-details" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                <h4 class="modal-title" id="myModalLabel">{{event.name}}</h4>
                            </div>
                            <form id="pay" name="pay" method="post" action="{% url 'users:payment' %}">
                                {% csrf_token %}
                                <div class="modal-body sam-purchase-modal-body">
                                {% for type in ticket_types %}
                                    {% include 'event_row_parts/event_row_purchase.html' with price=type.price ticket_type=type %}
                                {% endfor %}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">انصراف</button>
                                    <button type="submit" class="btn btn-success">پرداخت</button>
                                    <input type="hidden" id="event_{{event.id}}" name="event_id" value="{{event.id}}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

sam/templates/event_page.html
{% extends 'base.html' %}
{% load static %}
{% block google_map_hdr %}
    <script
        src="http://maps.googleapis.com/maps/api/js">
        </script>

        <script>
        function initialize() {
          var mapProp = {
            center:new google.maps.LatLng({{ event.latitude }},{{ event.longitude }}),
            zoom:15,
            mapTypeId:google.maps.MapTypeId.ROADMAP
          };
          var map=new google.maps.Map(document.getElementById("googleMap"), mapProp);
            var marker = new google.maps.Marker({
              position: new google.maps.LatLng({{ event.latitude }},{{ event.longitude }}),
              map: map
            });
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
{% endblock %}


{% block main_column %}
<div class="row">
    {% include 'event_big_card.html' %}
</div>
<div class="row">
    {% include 'event_info_addr_card.html' %}
</div>

{% endblock %}


{% block body_tail %}
<script>
    $.fn.raty.defaults.path = "{% static 'frameworks/raty/lib/images' %}";
    $('.raty-star').raty();
</script>
{% endblock %}

sam/templates/event_small_card.html
{% load static %}
{% load farsi_num %}
<html>
    <head>
    </head>
    <body>
        {% load static %}
        <div class="thumbnail">
            <a href= {% url 'events:event_view' event.id %}>
                <img class="img-responsive img-rounded" src="{{ event.first_picture.picture.url }}" />
            </a>

            <div class="caption">
                <a href= {% url 'events:event_view' event.id %}>
                    <h4> {{ event.name }}
                    </h4>
                    <small class="badge"> {{ event.neighborhood }}</small>
                </a>
            </div>
            <div class="row sam-event-small-card-detail">
                    <div class="col-md-6 ">
                       <div class="raty-star"></div>
                    </div>
                    <div class="col-md-4 col-md-offset-2 ">
                        {{ event.sold_tickets_number|farsi_num }} <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                    </div>
            </div>
        </div>
    </body>
</html>

sam/templates/footer.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <div class="responsive row">
            <div class="row">
                <div class="col-md-4 sam-align-right">
                    <h5>
                        حق طبع و نشر
                    </h5>
                    <h5>
                        استفاده از مطالب سایت سام فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع است.
                    </h5>
                    <h5>
                        کلیه حقوق این سایت متعلق به شرکت سامانه‌پردازان سام می‌باشد.
                    </h5>
                </div>
                <div class="col-md-4 sam-align-center">
                </div>
                <div class="col-md-4 sam-align-left">
                    <h5>
                        تماس با ما
                    </h5>
                    <h5>
                        آدرس: تهران، خیابان آزادی، دانشگاه صنعتی شریف، دانشکده مهندسی کامپیوتر
                    </h5>
                    <h5>
                        تلفن: ۶۶۶۵۲۲۲۳-۰۲۱
                    </h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 sam-align-center">
                    <h6>
                        Copyright
                        <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span>
                        2015-2017 Saam
                    </h6>
                </div>
            </div>
        </div>
    </body>
</html>

sam/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block right_sidebar %}
    {% include 'right_sidebar_menu.html' with categories=categories %}
{% endblock%}
{% block main_column %}
<div class="row">
    {% include 'event_big_card.html' with event=event types=types%}
</div>
<div class="well">
    <h3>جدیدترین‌ها</h3>
    <div class="row">
        {% for event in newevents %}
        <div class="col-md-4 sam-border">
            {% include 'event_small_card.html' with event=event %}
        </div>
        {% endfor %}
    </div>
</div>
<div class="well">
    <h3>محبوب‌ترین‌ها</h3>
    <div class="row">
        {% for event in popularevents %}
        <div class="col-md-4 sam-border">
            {% include 'event_small_card.html' with event=event %}
        </div>
        {% endfor %}
    </div>
</div>
<div class="well">
    <h3>پرفروش‌ترین‌ها</h3>
    <div class="row">
        {% for event in topsellerevents %}
        <div class="col-md-4 sam-border">
            {% include 'event_small_card.html' with event=event %}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

sam/templates/printable_ticket.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <link rel="shortcut icon" href="{% static 'frameworks/bootstrap-rtl/bootstrap/docs/favicon.ico' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'frameworks/bootstrap-rtl/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap RTL theme -->
    <link href="{% static 'frameworks/bootstrap-rtl/dist/css/bootstrap-rtl.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'frameworks/bootstrap-rtl/bootstrap/dist/css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'frameworks/bootstrap-rtl/examples/rtl/rtl.css' %}" rel="stylesheet">

    <link href="{% static 'css/main_style_sheet.css' %}" rel="stylesheet">

</head>
<body>
<div class="row"></div>
<div class="col-md-6 col-md-offset-3">
    {% for ticket in tickets %}
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>{{ticket.event.name}}</th>
                <th>{{ticket.event.neighborhood}}</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>خریدار</td>
                <td>{{ticket.order.customer.userInfo.user.get_full_name}}</td>
            </tr>
            <tr>
                <td>شرکت فروشنده</td>
                <td>{{ticket.event.dealer.userInfo.user.username}}</td>
            </tr>
            <tr>
                <td>قیمت</td>
                <td>{{ticket.type.price}} تومان</td>
            </tr>
            <tr>
                <td>صندلی</td>
                <td>ردیف {{ticket.row}}، صندلی {{ticket.column}}</td>
            </tr>
            </tbody>
        </table>
        <br>
    {% endfor %}
</div>
</body>

sam/templates/right_sidebar_menu.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        {% load module %}
        <div class="panel-group" id="accordion">
            {% for cat in categories %}
            <div class="panel panel-default cat{{ cat.id|module }}">
                <div class="panel-heading">
                    <div class="row">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ cat.id }}">
                                <div class="col-md-12">
                                    <span class="glyphicon glyphicon-stop">
                                    </span>{{ cat.name }}
                                </div>
                            </a>
                        </h4>
                    </div>
                </div>
                <div id="collapse{{ cat.id }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <table class="table">
                            <tbody>
                        {% for subcat in cat.subcategory_set.all %}
                                <tr>
                                    <td>
                                        <a href="{% url 'events:show_subcategory' cat.id subcat.id %}">
                                            <div class="col-md-12">
                                                <span class="glyphicon glyphicon-minus text-primary"></span>{{subcat.name}}
                                            </div>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                                <tr>
                                    <td>
                                        <a href="{% url 'events:show_subcategory' cat.id 0 %}">
                                            <div class="col-md-12">
                                                <span class="glyphicon glyphicon-minus text-primary"></span>همه
                                            </div>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% if offered_events|length > 0 %}
                <div class="row sam-offered-events">
                    <div class="col-md-12 ">
                      <div class="col-md-12  thumbnail">
                          <h4>{{ side_bar_offer_topic }}</h4>

                          {% for item in offered_events %}
                              {% include "event_small_card.html" with event=item %}
                          {% endfor %}
                      </div>
                   </div>
                </div>
            {% endif %}
        </div>
    </body>
</html>

sam/templates/right_sidebar_profile_dealer.html
{% extends 'right_sidebar_profile.html' %}
{% load static %}

{% block image %}
    <img class="img-responsive img-circle" src="{{ profile_user.userInfo.picture.url }}">
{% endblock %}

{% block info %}
    <h3>{{ profile_user.userInfo.user.get_full_name }}</h3>
     <div class="row">
        <div class="col-md-4 sam-align-left-bold">
            نام کاربری
        </div>
        <div class="col-md-8 sam-align-right">
            {{ profile_user.userInfo.user.username }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 sam-align-left-bold">
            شماره ثبت
        </div>
        <div class="col-md-8 sam-align-right">
            {{ profile_user.registryNumber }}
        </div>
    </div>
    <!--<div class="row">
        <div class="col-md-4 sam-align-left-bold">
            وضعیت
        </div>
        <div class="col-md-8 sam-align-right">
            {{ profile_user.get_status }}
        </div>
    </div>-->
{% endblock %}
{% block button %}
    <div class="col-md-4">
    </div>
    <div class="col-md-8">
        <a href="{% url 'users:edit_profile' %}">
            <button type="button" class="btn btn-primary">ویرایش</button>
        </a>    
    </div>
 {% endblock %}

sam/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block main_column %}

    <div class="well">
        <h3>نتیجه ی جست و جو</h3>

        <div class="row">
            {% include 'event_small_card.html' %}
            {% include 'event_small_card.html' %}
            {% include 'event_small_card.html' %}
            {% include 'event_small_card.html' %}
            {% include 'event_small_card.html' %}
            {% include 'event_small_card.html' %}
        </div>
    </div>

{% endblock %}