sam/events/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register_event/$', views.register_event, name="register_event"),
    url(r'event_small_card/$', views.event_cards, name='event_small_card'),
    url(r'event_row_verify/$', views.event_row_verify, name='event_row_verify'),
    url(r'event_row_condition/$', views.event_row_condition, name='event_row_condition'),
    url(r'event_row_purchase/$', views.event_row_purchase, name='event_row_purchase'),
    url(r'event_row_print/$', views.event_row_print, name='event_row_print'),
    url(r'event_cards/$', views.event_cards, name='event_cards'),
    url(r'^edit_details/(?P<event_id>\d+)/$', views.edit_details, name="edit_details"),
    url(r'^edit_event/(?P<event_id>\d+)/(?P<done>\d+)$', views.event_edit_page, name='event_edit'),
    url(r'event_row_verify/$', views.event_row_verify, name='event_row_verify'),
    url(r'^remove_category/$', views.remove_category, name='remove_category'),
    url(r'^subcategory/(?P<category_id>([0-9])+)/(?P<subcategory_id>([0-9])+)/$', views.show_subcategory, name='show_subcategory'),
    url(r'^(?P<event_id>\d+)/$', views.event_view, name='event_view'),
    url(r'^delete_event/(?P<event_id>\d+)/$', views.delete, name='delete'),
    url(r'^info_template/', views.info_template, name="info_template"),
]

sam/sam/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static

from . import settings
import events.urls
import users.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include(users.urls, namespace="users")),
    url(r'^events/', include(events.urls, namespace="events"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sam/users/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^login/$', 'users.views.login', name="login"),
    url(r'^logout/$', 'users.views.logout', name="logout"),
    url(r'^test/signup', 'users.views.signup', name='signup'),
    url(r'^signup/customer', 'users.views.signup_customer', name='signup_customer'),
    url(r'^signup/dealer', 'users.views.signup_dealer', name='signup_dealer'),
    url(r'^home/$', 'users.views.home', name='home'),
    url(r'^show_profile/$', 'users.views.show_profile', name='show_profile'),
    url(r'^ticket/(?P<return_code>\d+)/$', 'users.views.print_ticket', name='ticket'),
    url(r'^test/home/user/$', 'users.views.home_log_out', name='homelogout'),
    url(r'^payment/successful/$', 'users.views.payment_success', name='success'),
    url(r'^payment/$', 'users.views.payment', name='payment'),
    url(r'^cancel_payment/$', 'users.views.cancel_payment', name='cancel_payment'),
    url(r'^test/search/category/subcategory/$', 'users.views.search', name='testsearch'),
    url(r'^test/menu/$', 'users.views.menu', name='test'),
    url(r'^test/customer/$', 'users.views.customer_profile', name='test_customer'),
    url(r'^test/dealer/$', 'users.views.dealer_profile', name='test'),
    url(r'^test/admin/$', 'users.views.admin', name='test_admin'),
    url(r'^test/$', 'users.views.test', name='test'),
    url(r'^admin/$', 'users.views.admin', name='admin'),
    url(r'^profile/username', 'users.views.customer_profile', name='customer_profile'),
    url(r'^profile/dealer', 'users.views.dealer_profile', name='dealer_profile'),
    url(r'^add_category', 'users.views.add_category', name='add_category'),
    url(r'^add_subcategory', 'users.views.add_subcategory', name="add_subcategory"),
    url(r'^edit_category', 'users.views.edit_category', name="edit_category"),
    url(r'^edit_subcategory', 'users.views.edit_subcategory', name="edit_category"),
    url(r'^editCat/(?P<catpk>[-\w]+)/all_json_subs/$', 'users.views.all_json_subs'),
    url(r'^remove_subcategory', 'users.views.remove_subcategory', name="remove_category"),
    url(r'^removeCat/(?P<catpk>[-\w]+)/all_json_subs/$', 'users.views.all_json_subs'),
    url(r'^edit_profile', 'users.views.edit_profile', name='edit_profile'),
    url(r'^submit_edit_profile', 'users.views.submit_edit_profile', name='submit_edit_profile'),
    url(r'^admin_comment/', 'users.views.admin_comment', name="admin_comment"),
]

sam/templates/event_row_parts/event_row_condition.html
{%  extends 'event_row_base.html' %}
{% load farsi_num %}

{% block numberOfItems %}
   <div class="col-md-2">
        <h5>تعداد بلیت‌ها</h5>
        <div class="row">
            <div class="col-md-12">
                <h4>{{ event.total_number_of_tickets | farsi_num  }} عدد</h4>
            </div>
        </div>
    </div>
{% endblock %}

{%  block lastcell %}
<div class="col-md-1">
    <a href="{% url 'events:event_edit' event.id 0 %}"><button class="btn btn-default " type="button" title="بررسی وضعیت">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
    </button>
    </a>
    <div class="row">
        <div class="col-md-10">
            {% if event.condition == 1 %}
                <h4><span class="label label-danger">رد شده</span></h4>
            {% elif event.condition == 0 %}
                <h4><span class="label label-success">تایید</span></h4>
            {% else %}
                <h4><span class="label label-warning">انتظار</span></h4>
            {% endif %}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{%  endblock %}

sam/templates/event_row_parts/event_row_condition_dealer.html
{%  extends 'event_row_base.html' %}
{% load farsi_num %}

{% block numberOfItems %}
   <div class="col-md-2">
        <h5>تعداد بلیت‌ها</h5>
        <div class="row">
            <div class="col-md-12">
                <h4>{{ event.total_number_of_tickets | farsi_num  }} عدد</h4>
            </div>
        </div>
    </div>
{% endblock %}

{%  block lastcell %}
<div class="col-md-1">
    <a href="{% url 'events:edit_details' event.id %}"><button class="btn btn-default " type="button" title="بررسی وضعیت">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
    </button>
    </a>
    <div class="row">
        <div class="col-md-10">
            {% if event.condition == 1 %}
                <h4><span class="label label-danger">رد شده</span></h4>
            {% elif event.condition == 0 %}
                <h4><span class="label label-success">تایید</span></h4>
            {% else %}
                <h4><span class="label label-warning">انتظار</span></h4>
            {% endif %}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{%  endblock %}

sam/templates/event_row_parts/event_row_delete.html
{%  extends 'event_row_base.html' %}

{% block numberOfItems %}
   <div class="col-md-2">
        <h5>تعداد بلیت‌ها</h5>
        <div class="row">
            <div class="col-md-12">
                <h4>{{ event.total_number_of_tickets }}عدد</h4>
            </div>
        </div>
    </div>
{% endblock %}

{%  block lastcell %}
<div class="col-md-1">
    <div class="row">
    </div>
    <h5></h5>
    <a href="{% url 'events:delete' event.id %}"><button class="btn btn-danger " type="button" title="حذف">
        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
    </button></a>
</div>
{%  endblock %}

sam/templates/event_row_parts/event_row_print.html
{% load static %}
{% load farsi_num %}

<div class="col-md-12 thumbnail">
    <div class="row">
        <div class="col-md-2">
            <a href= {% url 'events:event_view' order.event.id %}>
            <img class="img-responsive img-rounded" src="{{ order.event.first_picture.picture.url }}"/>
            </a>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-3">
                    <h5>{{ order.event.first_date | farsi_num}}</h5>
                </div>
                <div class="col-md-9">
                    <div class="col-md-2">
                        <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                    </div>
                    <h5>{{ order.event.neighborhood | farsi_num }}</h5>
                </div>
            </div>
                        <a href= {% url 'events:event_view' order.event.id %}>
            <h4>{{ order.event.name }}</h4>
            </a>
        </div>
        <div class="col-md-4">
            <h5>فروشنده</h5>
            <div class="row">
                <div class="col-md-12">
                    {% if order.event.dealer.userInfo.user.get_full_name|length > 0 %}
                        <h4>{{ order.event.dealer.userInfo.user.get_full_name }}</h4>
                    {% else %}
                        <h4>-</h4>
                    {% endif %}
                </div>
            </div>
        </div>
        {% block lastcell %}
        <div class="col-md-2">
            <div class="row">
            </div>
            <h5></h5>
            <a href="{% url 'users:ticket' order.id %}" target="_blank">
            <button class="btn btn-default " type="button" title="چاپ بلیت">
                <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
            </button>
            </a>
        </div>
        {%  endblock %}
    </div>
</div>

sam/templates/event_row_parts/event_row_purchase.html
{%  extends 'event_row_base.html' %}

{% block numberOfItems %}
{% endblock %}

{%  block lastcell %}
<div class="col-md-1">
    <div class="row" style="padding-right:15px">
        <h5>تعداد</h5>
    </div>
    <div class="row">
        <div class="col-md-12 sam-align-right">
            <input type="number" name="type_{{ ticket_type.id }}" id="type_{{ ticket_type.id }}" style = "padding:0; padding-right: 5px;" min="0" max="{{ticet_type.available}}" class="form-control" placeholder="0">
        </div>
    </div>
</div>
<!--
<div class="col-md-2">
    <h5>مجموع</h5>
    <div class="row">
        <div class="col-md-12">
            <h4>?</h4>
        </div>
    </div>
</div>
-->
{%  endblock %}

sam/templates/event_row_parts/event_row_report_buy.html
{% extends 'event_row_base.html' %}

{% block price %}
<div class="col-md-2">
    <h5>قیمت کل</h5>
    <div class="row">
        <div class="col-md-12">
            <h4>۱۲۰۰۰۰ تومان</h4>
        </div>
    </div>
</div>
{% endblock %}

{% block numberOfItems %}
{% endblock %}

{% block lastcell %}
<div class="col-md-2">
    <h5>خریدار</h5>
    <div class="row">
        <div class="col-md-12">
            <h4>نام خریدار</h4>
        </div>
    </div>
</div>
{% endblock %}

sam/templates/event_row_parts/event_row_showing_user.html
{%  extends 'event_row_base.html' %}

{% block numberOfItems %}
{% endblock %}

{%  block lastcell %}
<div class="col-md-1">
    <h5>تعداد</h5>
    <div class="row">
        <div class="col-md-12">
            <h4> ۵ </h4>
        </div>
    </div>
</div>
<div class="col-md-2">
    <h5>مجموع</h5>
    <div class="row">
        <div class="col-md-12">
            <h4>۱۰۰۰۰۰۰ تومان</h4>
        </div>
    </div>
</div>
{%  endblock %}

sam/templates/event_row_parts/event_row_verify.html
{%  extends 'event_row_base.html' %}

{%  block lastcell %}
<div class="col-md-1">
    <div class="row">
    </div>
    <h5></h5>
    <a href="{% url 'events:event_edit' event.id 0 %}"><button class="btn btn-default " type="button" title="بررسی وضعیت">
        <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
    </button>
    </a>
</div>

{%  endblock %}