sam/sam/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static

from . import settings
import events.urls
import users.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include(users.urls, namespace="users")),
    url(r'^events/', include(events.urls, namespace="events"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sam/users/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^login/$', 'users.views.login', name="login"),
    url(r'^logout/$', 'users.views.logout', name="logout"),
    url(r'^test/signup', 'users.views.signup', name='signup'),
    url(r'^signup/customer', 'users.views.signup_customer', name='signup_customer'),
    url(r'^signup/dealer', 'users.views.signup_dealer', name='signup_dealer'),
    url(r'^home/$', 'users.views.home', name='home'),
    url(r'^show_profile/$', 'users.views.show_profile', name='show_profile'),
    url(r'^ticket/(?P<return_code>\d+)/$', 'users.views.print_ticket', name='ticket'),
    url(r'^test/home/user/$', 'users.views.home_log_out', name='homelogout'),
    url(r'^payment/successful/$', 'users.views.payment_success', name='success'),
    url(r'^payment/$', 'users.views.payment', name='payment'),
    url(r'^cancel_payment/$', 'users.views.cancel_payment', name='cancel_payment'),
    url(r'^test/search/category/subcategory/$', 'users.views.search', name='testsearch'),
    url(r'^test/menu/$', 'users.views.menu', name='test'),
    url(r'^test/customer/$', 'users.views.customer_profile', name='test_customer'),
    url(r'^test/dealer/$', 'users.views.dealer_profile', name='test'),
    url(r'^test/admin/$', 'users.views.admin', name='test_admin'),
    url(r'^test/$', 'users.views.test', name='test'),
    url(r'^admin/$', 'users.views.admin', name='admin'),
    url(r'^profile/username', 'users.views.customer_profile', name='customer_profile'),
    url(r'^profile/dealer', 'users.views.dealer_profile', name='dealer_profile'),
    url(r'^add_category', 'users.views.add_category', name='add_category'),
    url(r'^add_subcategory', 'users.views.add_subcategory', name="add_subcategory"),
    url(r'^edit_category', 'users.views.edit_category', name="edit_category"),
    url(r'^edit_subcategory', 'users.views.edit_subcategory', name="edit_category"),
    url(r'^editCat/(?P<catpk>[-\w]+)/all_json_subs/$', 'users.views.all_json_subs'),
    url(r'^remove_subcategory', 'users.views.remove_subcategory', name="remove_category"),
    url(r'^removeCat/(?P<catpk>[-\w]+)/all_json_subs/$', 'users.views.all_json_subs'),
    url(r'^edit_profile', 'users.views.edit_profile', name='edit_profile'),
    url(r'^submit_edit_profile', 'users.views.submit_edit_profile', name='submit_edit_profile'),
    url(r'^admin_comment/', 'users.views.admin_comment', name="admin_comment"),
]

sam/templates/navbar_parts/nav_bar.html
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="col-md-12 container">
        <div class="col-md-4 sam-align-center">
            {% if user.is_authenticated %}
                {% include 'navbar_parts/nav_bar_logout.html' %}
            {% else %}
                {% include 'navbar_parts/nav_bar_login.html' %}
            {% endif %}
        </div>
        <div class="col-md-4 sam-align-center">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <a href="{%  url 'users:home' %}">
                    <img class="img-responsive" src="/static/tmp_media/sam_logo_black_small.png" style="display:inline">
                </a>
            </div>
        </div>
        <div class="col-md-4 sam-align-center">
            <div class="col-md-1"></div>
            <form class="navbar-form col-md-9" role="search">
                <div class="input-group col-md-12">
                    <input type="text" class="form-control" placeholder="جست و جوی رویدادها" name="srch-term" id="srch-term">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
        <!--/.nav-collapse -->
    </div>
</div>

sam/templates/navbar_parts/nav_bar_login.html
<div class="sam-align-center">
    <div class="col-md-2"></div>
    <div class=" col-md-9 btn-group sam-login-logout" role="group" aria-label="..." style="padding-top: 2%">
        <a href="{% url 'users:signup' %}" class="btn btn-default col-md-6" >
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    ثبت نام
        </a>
        <a href="{% url 'users:login' %}" id="userBtn" class="btn btn-default col-md-6">
ورود

        </a>
    </div>
</div>

sam/templates/navbar_parts/nav_bar_logout.html
<div class="sam-align-center">
    <div class="col-md-2"></div>
    <div class=" col-md-9 btn-group sam-login-logout" role="group" aria-label="..." style="padding-top: 2%">
        <a href=" {% url 'users:show_profile' %} " id="userBtn" class="btn btn-default col-md-6" type="button" class=" btn btn-default">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    حساب کاربری
        </a>

        <a href=" {% url 'users:logout' %}" id="userBtn" class="btn btn-default col-md-6" type="button" class=" btn btn-default">
    خروج
        </a>
    </div>
</div>